apiVersion: certmanager.k8s.io/v1/alpha1
kind: ClusterIssuer
metada:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: brianf.baez8@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
